### ISSUE TITLE
Micro Service Architecture에 대한 실 적용방안

### ISSUE THREAD

**Issue by papillon212** [slow-programming/study#4]
- MSA란 무엇이며 SOA와의 차이점
- Internal API를 RESTful Service를 기반으로 구축하는 것이 과연 효율적인가?
- 대안책은 무엇인가?

**Comment by rim-dohyoung** [comment]
MSA와 SOA의 차이점

MSA는 SOA와 직접 비교 대상은 아니고, 기술적 단계의 선후 관계 정도 인것 같네요.
기존 한덩어리의 스트럭쳐를 서비스 단위로 하자는 것이 SOA이고,
그 서비스를 micro하게 잘게 쪼개자는 것이고.

기존에는 분산된 환경에서 개별 서비스를 제공 운영하는 기술적 기반이 부족해서 SOA라는 개념이 대두되었지만,
이제는 service는 너무 당연한 것이 되어버렸고, 모든 것이 SOA가 된 상황이죠.

internal API를 RESTful로?

주관적인 의견은, RESTful이건 무엇이건 간에 API로 잘 제공되고, 쉽게 사용할 수 있는 것이 최우선 같습니다. 기술이 문제가 아니죠.
기존에 CORBA라던가 뭐뭐라던가 있었지만, 어렵고 불편하고해서 잘 활용 안되었죠. RESTful의 최대 장점은 쉽!다! 입니다. 핵심 코어 개발이라면 다른 방식을 고려해봐야 하겠지만, 이러저러한 개발자들이 보편적으로 사용하려면 쉬운 RESTful이 짱이죠. 효율 보다는 널리 쓰임이 더 핵심 같네요.

**Comment by papillon212** [comment]
그럼 다음 주제로 선정하겠습니다~

**Comment by sh1nj1** [comment]
:+1:
